immutable_words = {
    'eax': 'EAX',
    ' ax ': ' AX ',
    'ecx': 'ECX',
    'hyung-nim': 'Hyung-Nim',
    'song-yi': 'Song-Yi',
    'i ': 'I ',
    'jin-ho': 'Jin-Ho',
    'min byeong-gu': 'Min Byeong-Gu',
    'oio': 'did',
    'ape': 'are',
    'shoulon’t': 'shouldn\'t',
    'oid': 'did',
    'yoo-jin': 'Yoo-Jin',
    'baek yoon-ho': 'Baek Yoon-Ho',
    '6uy': 'guy',
    'wilo': 'wild',
    'sung il-hwan': 'Sung Il-Hwan',
    ' mov ': ' MOV ',
    ' dword ': ' DWORD ',
    ' add ': ' ADD ',
    ' sub ': ' SUB ',
    '[edx]': '[EDX]',
    ' edx ': ' EDX ',
    ' 4iv ': ' DIV ',
    ' mu1 ': ' MUL ',
    ' mu1, ': ' MUL, ',
    ' edx. ': ' EDX. ',
    ' aiv ': ' DIV ',
    ' mu1\'s ': ' MUL\'s ',
    ' div ': ' DIV ',
}

spec_letters = {'\'', ',', '.', '!'}
